name = "workers-email-archiver"
main = "src/index.js"
compatibility_date = "2024-09-02"

[vars]
# S3_ACCESS_KEY set in console as secret
# S3_ACCESS_SECRET set in console as secret
S3_BUCKET = "dmsh"
S3_ENDPOINT = "j7w8.ch.idrivee2-42.com"

[limits]
cpu_ms = 30000

[observability]
enabled = true