name = "workers-email-archiver"
main = "src/index.js"
compatibility_date = "2024-09-02"

[vars]
# S3_ACCESS_KEY set in console as secret
# S3_ACCESS_SECRET set in console as secret
S3_BUCKET = "dmsh-v2"
S3_ENDPOINT = "r8i7.va.idrivee2-19.com"
S3_REGION = "VA"

[limits]
cpu_ms = 30000

[observability]
enabled = true

[placement]
mode = "smart"